apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::646686677518:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EXDE5TLLW5B9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::646686677518:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-12T04:54:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1532"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 818c5e50-2f1d-4e14-b50a-2eabb24e2855
